name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Buildozer
        uses: kivy/buildozer-action@v1.5.0
        with:
          buildozer_version: master
          buildozer_command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: jarvis-app
          path: bin/*.apk
