name: Build
on: [push]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ArtemSerebrenninkov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: jarvis-app
          path: ./*.apk
